#!/bin/bash


echo $GTEST_OUTPUT
export GTEST_OUTPUT=xml:/autograder/source/out.xml
cd /autograder/submission

cmake CMakeLists.txt

make
if [ $? != 0 ]; then
	cd /autograder/source
	./grader.py compileError > /autograder/results/results.json
	exit
fi


timeout 3m ./runTests
if [ $? != 0 ]; then
	cd /autograder/source
	./grader.py infiniteError > /autograder/results/results.json
	exit
fi


cd /autograder/source
./grader.py > /autograder/results/results.json
cat /autograder/results/results.json
